dns_providers = {"awsdns": "Amazon Route 53",
                 "cscdns": "CSC DNS Service",
                 "ja.net": "JANET",
                 "cloudflare.com": "CloudFlare",
                 "rackspace.com": "Rackspace",
                 "netnames.net": "CSC Global",
                 "livedns.co.uk": "Fasthosts Internet Ltd",
                 "xssl.net": "United Communications Ltd",
                 "mainnameserver.com": "Host Europe Group",
                 "dns.gxn.net": "GX Networks (Daisy Communications Ltd)",
                 "dns.daisygroup.net.":"Daisy Communications",
                 "myukcloud.com": "UK Dedicated",
                 "star.co.uk": "Star Technology Services",
                 "gradwellcloud.com": "Gradwell Communications Ltd",
                 "virginmedia.net": "Virgin Media",
                 "mylhns.net": "Lithium Holdings (Public Domain Registry)",
                 "pipex.net": "Pipex",
                 "offsitecloud.co.uk": "1 and 1 Internet SE",
                 "totalnameservers.com": "Total Web Solutions",
                 "spectrum-internet.co.uk": "Spectrum Internet",
                 "spectruminternet.com": "Spectrum Internet",
                 "onlineperspectives.co.uk": "Online Perspectives",
                 "dnsmatrix-python.co.uk": "BestHost",
                 "easynet.co.uk": "Easynet",
                 "hyperlink-interactive.co.uk": "Hyperlink",
                 "nimbushosting.co.uk": "Nimbus Hosting Ltd",
                 "cw.net": "Vodafone",
                 "domaincontrol.com": "Go Daddy",
                 "datacenta.net": "Datacenta Hosting",
                 "exponential-e.net": "Total Registrations",
                 "phase8.net": "Namesco Ltd",
                 "ukfast.net": "UKFast.net",
                 "idnet.net": "IDnet",
                 "hbpserver.net": "HBP SYSTEMS LTD",
                 "heartinternet.co.uk": "Heart Internet",
                 "heartinternet.uk": "Heart Internet",
                 "buckspsn.org.uk": "Updata",
                 "hcidata.com": "HCI Data",
                 "positive-internet.com": "Positive Internet Company",
                 "interdns.co.uk": "Inter DNS",
                 "wixdns.net": "Wixpress Ltd",
                 "wix.com": "Wix.com",
                 "bt.net": "BT",
                 "amahost.net": "Grade1 Internet Solutions",
                 "avecoh.com": "Atlantic Vision",
                 "namecity.com": "iomart Group",
                 "wirral-education.org.uk": "Metropolitan Borough of Wirral",
                 "lightning1.net": "123connect Ltd",
                 "opal-solutions.com": "Opal Business Solutions",
                 "netwisetraining.com": "Netwise Training",
                 "wnl.net": "Swansea University",
                 "wrexham.gov.uk": "Wrexham County Borough Council",
                 "easy-internet.co.uk": "Easy Internet Solutions",
                 "net-work.net": "Net-Work Internet",
                 "nics.gov.uk": "Northern Ireland Civil Service",
                 "kingston-internet.co.uk": "KCOM Group Plc",
                 "cloudhosting.co.uk": "Smart Cloud Hosting UK Ltd",
                 "walsall.gov.uk": "Walsall Metropolitan Borough Council",
                 "metoffice.gov.uk": "The Meteorological Office",
                 "meto.gov.uk": "Meteorological Office",
                 "stabletransit.com": "Rackspace",
                 "eliteukserve.net": "Elite Limited",
                 "clara.net": "Claranet UK Ltd",
                 "swisp.co.uk": "SWT NETWORKS LTD",
                 "e2bn": "East of England Broadband Network",
                 "adns.mdnx.net": "Easynet Global Services",
                 "34sp.com": "34SP.com Ltd",
                 "swebhosting.co.uk": "Seiretto Ltd",
                 "safenames.org": "International Administrator",
                 "kpsn.co.uk": "Kent County Council",
                 "tsohost.co.uk": "Paragon Internet Group",
                 "quick-hosts.com": "Hosting UK",
                 "cloudnext.net": "Cloud Next Ltd",
                 "onyx.net": "Onyx Information Technology Holdings",
                 "blacknovadesigns.co.uk": "Domain Manager",
                 "as12513.net": "Eclipse Networking",
                 "pair.com": "Pair Networks",
                 "dundeecity.gov.uk": "Dundee City Council",
                 "netzoomi.net": "Nexus Data Systems",
                 "dnsmatters.co.uk":"NetMatters",
                 "uk-noc.com":"WHOIS PRIVACY PROTECTION SERVICE, INC",
                 "firstserv.com":"Concert Networks Ltd",
                 "azure-dns":"Microsoft",
                 "bdm.microsoftonline.com": "Microsoft Corporation",
                 "ednet.co.uk":"Lumison Ltd",
                 "honeystone.com":"Honeystone Consulting Ltd",
                 "eclipse.net.uk":"Eclipse Networking",
                 "ifl.net": "RM PLC",
                 "dgexternal.net": "Dumfries and Galloway Council",
                 "vidacloud.co.uk":"Paragon Internet Group",
                 "aesrapidswitch.com":"AES Digital Solutions Ltd",
                 "name-services.com":"ENOM, INC.",
                 "domainmonster.com":"Domainmonster Ltd",
                 "extramsp.com":"Xtraordinary Networks Limited",
                 "demysdns":"Demys Limited",
                 "newnet.co.uk":"NewNet plc",
                 "weblever.co.uk":"Alec Moss",
                 "ukhost4u.com":"UKHOST4U.COM",
                 "scotland.net":"Scotland On Line",
                 "qinetiq-tim.net":"QinetiQ",
                 "dns.griffin.com":"Easynet Global Services",
                 "hants.gov.uk":"Hampshire County Council",
                 "krystal.co.uk":"Krystal Hosting Ltd Alta Vista",
                 "south-ayrshire.gov.uk":"South Ayrshire Council",
                 "trafford.gov.uk":"Trafford Metropolitan Borough Council",
                 "staffordshire.gov.uk":"Staffordshire County Council",
                 "izrsolutions.com":"izR Solutions Ltd",
                 "lumison.net":"Pulsant LTD",
                 "mh-p.net":"mh-p internet limited",
                 "dmpriest.net.uk":"D M Priest & Co Limited",
                 "wiserhosting.co.uk":"Now Enterprise",
                 "demysdns.net":"Demys Limited",
                 "srv.host-it.co.uk":"Nuco Technologies Limited",
                 "carrerauk-dns.co.uk": "gary mullineaux",
                 "networkdns.biz": "Domain Admin",
                 "zoneedit.com": "easyZone Acquisition Corp.",
                 "dnshostnetwork.com": "HOST MEDIA",
                 "swbroadband.co.uk": "South West Broadband",
                 "zen.co.uk": "Zen Internet Ltd",
                 "pulsant.com": "Pulsant Limited",
                 "bsky.ne.": "Blue Sky Hosting Ltd",
                 "r3u.rimnet3.co.uk": "Identity Protect Limited",
                 "civicahosting.co.uk": "Civica UK LTD",
                 "rochfordparishcouncil.gov.uk": "Rochford Parish Council",
                 "as12703.net": "Pulsant (formerly Lumison Limited)",
                 "phe.org.uk": "Health Protection Agency",
                 "vps183536-1.lcnservers.com": "Advantage Interactive Ltd",
                 "bb-online.net": "BB Online Limited",
                 "stackdns.com": "Contact Privacy Inc. Customer 0142166980",
                 "seegreen.net": "See Green Media Ltd.",
                 "pembrokeshire.gov.uk": "Pembrokeshire County Council",
                 "ovh.net":"OVH Sas",
                 "unlimited.uk.net":"Identity Protection Service",
                 "zengenti.com": "Zengenti Ltd",
                 "hyve.com": "HYVE MANAGED HOSTING",
                 "stmarybourne-pc.gov.uk": "St Mary Bourne Parish Council",
                 "dns.dyn.com": "Dyn",
                 "hertsgfl.org.uk": "Updata Infrastructure",
                 "eqsn.com": "EQSN Ltd",
                 "dynect.net": "Dyn",
                 "connectinternetsolutions.com": "Connect Internet Solutions",
                 "staffs.ac.uk": "Staffordshire University",
                 "plusnet.co.uk":"PlusNet plc",
                 "mythic-beasts.com":"Mythic Beasts",
                 "razorblue.com.":"Razorblue Group Ltd",
                 "jabhosting.com": "Jab Hosting",
                 "theso.co.uk": "The Stationery Office Limited",
                 "ahead4dns.com": "Ahead4 Ltd",
                 "wordpress.com": "Automattic, Inc.",
                 "redstone-isp.net": "Redstone Plc",
                 "blue-earth.co.uk": "Blue Earth",
                 "qzxyz.com": "Atomwide Ltd",
                 "peterborough.gov.uk": "Peterborough City Council",
                 "bb-online.co.uk": "BB Online Ltd",
                 "absolutelypc.co.uk": "Absolutely PC Ltd",
                 "somerset.gov.uk": "Somerset County Council",
                 "scotborders.gov.uk": "Scottish Borders Council",
                 "hostinguk.net": "Internet Engineering Ltd",
                 "this-dns.net": "Astutium Limited",
                 "backboneconnect.co.uk": "Backbone Connect",
                 "aber.ac.uk": "University of Wales, Aberystwyth",
                 "senior.co.uk": "Senior Internet Ltd",
                 "dnsmadeeasy.com": "Tiggee",
                 "renfrewshire.gov.uk": "Renfrewshire Council",
                 "ed.ac.uk": "The University of Edinburgh",
                 "catalyst2.net": "Catalyst2 Services Ltd",
                 "vmdns.co.uk": "Vantech Media",
                 "ns247.net": "M247 Ltd",
                 "seirettonameservers.co.uk": "Seiretto Ltd",
                 "vhdns.net": "Vidahost",
                 "vidahost.com": "Paragon Internet Group",
                 "pipedns.com": "THE ENDURANCE INTERNATIONAL GROUP",
                 "interdirect.co.uk": "Interdirect Limited",
                 "designsomerset.com": "No Org",
                 "dreamhost.com": "PROXY PROTECTION LLC",
                 "aq.net.uk": "(aq) networks limited",
                 "eastdnsserver.com": "East Web and Print Ltd",
                 "jolora.com": "Jolora",
                 "kantara.net": "Kantara Limited",
                 "knibs.net": "Kantara Limited",
                 "nynet.co.uk": "NYnet Ltd",
                 "ultradns.biz": "Neustar",
                 "ultradns.net": "Neustar",
                 "eukdns.com": "EUKHOSTS Ltd",
                 "cloudbuy.com": "cloudBuy",
                 "nviron.net": "No Org",
                 "edscot.net": "Education Scotland",
                 "gradwell": "Gradwell Communications Ltd",
                 "stirling.gov.uk": "Stirling Council",
                 "pointhq.com": "PointDNS",
                 "contactonlineltd.co.uk": "Contact Online Ltd",
                 "enta.net": "Entanet International Ltd",
                 "wyehosts.net": "Wyehost Ltd",
                 "wyehosts.co.uk": "Wyehost Ltd",
                 "barkweb.co.uk": "BarkWeb Ltd",
                 "dl.ac.uk": "Daresbury Laboratory",
                 "rotherham.gov.uk": "Rotherham Metropolitan Borough Council",
                 "intouchsystems.co.uk": "InTouch Systems",
                 "freeola.net": "Freeola Ltd",
                 "myrem.uk": "Razor Edge Media Ltd",
                 "dumgal.gov.uk": "Dumfries and Galloway Council",
                 "force36.net": "Force36 Ltd",
                 "supremeservers.co.uk": "CompuWeb Communications Services Ltd",
                 "dedipower.net": "Pulsant",
                 "sandwell.gov.uk": "Sandwell Metropolitan Borough Council",
                 "denbighshire.gov.uk": "Denbighshire County Council",
                 "ictservices.co.uk": "Salford City Council",
                 "antechsmail.co.uk":"Antechs St Ives Ltd (Host Europe Group)",
                 "wpmanagedhost.com":"Envato Pty Ltd",
                 "colt": "Colt Technology Services",
                 "safenames.net": "Safenames Ltd",
                 "safenames.com": "Safenames Ltd",
                 "biznetservers.com": "BIZNET IIS LTD",
                 "xcalibre.co.uk": "Flexiant Ltd",
                 "vi.net": "Virtual Internet (UK) Ltd",
                 "LIGHTNING1.NET": "123connect Ltd",
                 "mydns0.uk": "The Phone Co-op",
                 "mydns1.uk": "The Phone Co-op",
                 "mydns2.uk": "The Phone Co-op",
                 "phonecoop.com": "The Phone Co-op",
                 "swan.ac.uk": "Swansea University",
                 "dns.pblin.net.":"Public Internet Limited",
                 "watchfront.net.uk":"Watchfront Limited",
                 "rushmoor.gov.uk": "Rushmoor Borough Council",
                 "defra.gov.uk": "Department for Environment, Food and Rural Affairs (Defra)",
                 "ns.bytemark.co.uk": "Bytemark Computer Consulting Ltd",
                 "server.ntli.net": "NTL Internet Ltd",
                 "force9.net": "PLUSNET PLC",
                 "one.formationdedicated.co.uk": "Formation Media Ltd",
                 "suffolk-fire.gov.uk": "Suffolk Fire and Rescue Service",
                 "ultradns.com": "NeuStar, Inc.",
                 "ultradns.org": "Security Group",
                 "domaincheck.co.uk": "Zebra Electronics Limited",
                 "fast.net.uk": "FastNet International Ltd",
                 "birmingham.gov.uk": "Birmingham City Council",
                 "dns.keme.net": "Timico Ltd",
                 "csdinternet.co.uk": "CSD Ltd",
                 "1and1-dns": "1&1 Internet AG",
                 "sseln.org.uk": "Stockport Metropolitan Borough Council",
                 "i51server.com": "Impress51",
                 "spitfireuk.net": "Spitfire Technology Group",
                 "future-shock.net": "Future Shock Ltd",
                 "swansea-edunet.gov.uk": "City and County of Swansea",
                 "swansea.gov.uk.": "City and County of Swansea",
                 "uk.atos.net": "ATOS SE",
                 "hostedservices.com": "WHOIS PRIVACY PROTECTION SERVICE",
                 "bsky.net": "Blue Sky Hosting",
                 "quksdns11.net": "Paragon Internet Group",
                 "essexschools.org.uk": "Essex County Council",
                 "inca-internet.com": "NAMECHEAP.COM",
                 "companieshouse.gov.uk": "Companies House",
                 "us-noc.com": "WHOIS PRIVACY PROTECTION SERVICE",
                 "shropshire.gov.uk": "Shropshire County Council",
                 "worldsecuresystems.com": "Adobe Systems Incorporated",
                 "oakfordhosting.com": "Oakford Technology",
                 "warwickshire.gov.uk": "Warwickshire County Council",
                 "dns.sccis.net": "Specialist Computer Centres",
                 "rapidswitch.com": "RapidSwitch Ltd",
                 "brunel.ac.uk": "Brunel University",
                 "bham.ac.uk": "The University of Birmingham",
                 "kcom.com": "KCOM Group",
                 "mistral.co.uk": "KCOM Group",
                 "flipsidedata.net": "Flipside Group",
                 "cloudns.net": "Cloud DNS Ltd",
                 "westsussex.gov.uk": "West Sussex County Council",
                 "onmedia.co.uk": "Avdec Ltd",
                 "redstone4business.co.uk": "Redstone Network Services Ltd",
                 "ruralwales.net": "Powys County Council",
                 "valeofglamorgan.gov.uk": "The Vale of Glamorgan Council",
                 "justhost.com": "ENDURANCE INTERNATIONAL GROUP, INC.",
                 "redbackinternet.net": "WEBHOSTING UK COM  LTD",
                 "updata.net": "1&1 Internet Limited",
                 "anlx.net": "Associated Networks (UK) Ltd",
                 "akam.net": "Akamai Technologies, inc.",
                 "conceptcoders.net": "Concept Coders Ltd",
                 "infotech247.com": "Infotech 24 7 Limited",
                 "uberns.net": "Total Uptime Technologies",
                 "uberns.com": "Total Uptime Technologies",
                 "fco.gov.uk": "Foreign & Commonwealth Office",
                 "medway.gov.uk": "Medway Council",
                 "netsupport.net": "NetSupport",
                 "ebizs.net": "E Business Services",
                 "hostgator.com": "HOSTGATOR",
                 "oh-isp.com": "Synetrix Holdings",
                 "tibus.net": "TIBUS Domain Hosting",
                 "carrierzone.com": "Deluxe Enterprise Operations",
                 "metoffice.com": "Met Office",
                 "bedford.gov.uk": "Bedford Borough Council",
                 "rochenhost.com": "Rochen Limited",
                 "hosteurope.com": "Host Europe Group",
                 "derwentside.net": "Derwentside District Council",
                 "primary-dns.co.uk": "Nominet UK",
                 "secondary-dns.co.uk": "Nominet UK",
                 "eastriding.gov.uk": "East Riding Of Yorkshire Council",
                 "e-riding.net": "East Riding of Yorkshire Council",
                 "websitewelcome.com.":"WHOIS PRIVACY PROTECTION SERVICE",
                 "northamptonshire.gov.uk": "Northamptonshire County Council",
                 "flintshire.gov.uk.": "Flintshire County Council",
                 "idp365.net": "Safenames Ltd",
                 "hscic.gov.uk": "Health and Social Care Information",
                 "exa-networks.co.uk": "Exa Networks",
                 "nseuk.net": "Net Solutions Europe Ltd",
                 "eechost.net": "Tollon Limited",
                 "dudley.gov.uk": "Dudley Metropolitan Borough Council",
                 "dns.net.uk": "Dark Group Ltd",
                 "hackney.gov.uk": "Hackney London Borough Council",
                 "harrow.gov.uk": "London Borough of Harrow",
                 "register.com": "Register.com",
                 "highland.gov.uk.":"The Highland Council",
                 "admbackup.co.uk": "ADM Computing",
                 "admcomputing.co.uk": "ADM Computing",
                 "cgfl.net": "Ceredigion County Council",
                 "cerenet.org.uk": "Ceredgion County Council",
                 "hotscot.co.uk": "Hotscot",
                 "bromley.gov.uk": "Bromley London Borough Council",
                 "merton.gov.uk": "London Borough of Merton",
                 "demon.co.uk": "Vodafone",
                 "demon.net.":"Vodafone Ltd",
                 "wizbit.net": "Wizbit Internet Services Ltd",
                 "brent.gov.uk": "London Borough of Brent",
                 "bfhosting.co.uk": "Big Fish Internet Limited",
                 "vibrantpulse.com": "Vibrant Pulse",
                 "sict-services.org.uk": "Schools ICT",
                 "alphadns.co.uk": "Alpha Business Communications Ltd",
                 "lewisham.gov.uk": "London Borough of Lewisham",
                 "midlandcomputers.com": "MIDLAND COMPUTERS LTD",
                 "elite-dns.net": "Web Wiz",
                 "elite-dns.co.uk": "Web Wiz",
                 "orkney.gov.uk": "Orkney Islands Council",
                 "leeds.gov.uk": "Leeds City Council",
                 "newham.gov.uk": "London Borough of Newham",
                 "north-ayrshire.gov.uk": "North Ayrshire Council",
                 "blacknest.gov.uk": "AWE Blacknest",
                 "argyll-bute.gov.uk": "Argyll & Bute Council",
                 "dns.uk.psi.net": "Cogent Communications",
                 "southampton.gov.uk": "Southampton City Council",
                 "qnop.net": "Paragon Internet Group",
                 "nethosted.co.uk": "NetHosted Ltd",
                 "portfast.net": "Portfast Ltd",
                 "toucaninternet.com": "Toucan Internet",
                 "basingstoke.gov.uk": "Basingstoke and Deane Borough Council",
                 "ulcc.ac.uk": "University of London Computer Centre",
                 "devon.gov.uk": "Devon County Council",
                 "eircomni.co.uk": "Eircom",
                 "aberdeenshire.gov.uk": "Aberdeenshire Council",
                 "thebunker.net": "The Bunker Secure Hosting Limited",
                 "ipo.gov.uk": "The UK Intellectual Property Office",
                 "csl.gov.uk": "Central Science Laboratory",
                 "cheshire.gov.uk": "Cheshire County Council",
                 "safeukdns.net": "UK2 GROUP",
                 "coopa.net": "COOPA LIMITED",
                 "togethertech.uk": "Together Technology",
                 "compulink.co.uk": "CIX Online",
                 "milton-keynes.gov.uk": "Milton Keynes Council",
                 "ukwebsolutionsdirect.com": "UKWEB.SOLUTIONSDIRECTLTD",
                 "mypremiumserver.com": "Freethought Internet",
                 "speednames.com": "NetNames Limited",
                 "nevisinternet.net": "Nevis Computers",
                 "abd-uk.com": "Rather Good Productions",
                 "edin.org": "City of Edinburgh Council",
                 "ccinf.org.uk": "Cornwall Council",
                 "streamlinedns.co.uk": "Fasthosts Internet",
                 "dns.vpwsys.net": "VPW Systems UK Ltd",
                 "serverhouse.co.uk": "Serverhouse",
                 "site5.com": "The Endurance International Group",
                 "wightfibre.com": "Wightcable 2005 Ltd",
                 "easydns.com": "easyDNS Technologies",
                 "hotchilli.net": "Hotchilli Internet",
                 "1and1.co.uk":"1 & 1 Internet",
                 "gridhost.co.uk": "Paragon Internet Group",
                 "angus.gov.uk": "Angus Council",
                 "dns-zones.net": "Datatech UK",
                 "westlothian.gov.uk": "West Lothian Council",
                 "admhosting.co.uk": "ADM Computing",
                 "bridgwaterwithout-pc.gov.uk": "Bridgwater Without Parish Council",
                 "stteathparishcouncil.gov.uk": "St Teath Parish Council",
                 "gconnect.net": "GConnect",
                 "cheshire-pcc.gov.uk": "Police and Crime Commissioner for Cheshire",
                 "xilo.net": "XILO COMMUNICATIONS",
                 "netnorth.net": "Netnorth Limited",
                 "netnorth.co.uk":"Netnorth Limited",
                 "nerc-swindon.ac.uk": "NERC",
                 "nerc-wallingford.ac.uk": "NERC",
                 "cloud.cardiffcouncilwebteam.co.uk": "Cardiff Council",
                 "3v0.net": "Paragon Internet Group",
                 "pipeten.co.uk": "Pipe Ten Hosting",
                 "ucl.ac.uk": "University College London",
                 "rsft.co.uk": "Roffesoft",
                 "clook.net": "SUB 6",
                 "setsquaresolutions.com": "Setsquare Creative Solutions",
                 "4uh.net": "4UH",
                 "rcahms.gov.uk": "Royal Commission on the Historic Monuments of Scotland",
                 "newmiltontowncouncil.gov.uk": "New Milton Town Council",
                 "taysidefire.gov.uk": "Tayside Fire Brigade",
                 "ysgolccc.org.uk": "Carmarthenshire IT Services",
                 "uberns.co.uk": "Jonathan Hoppe",
                 "drakonim.co.uk": "Drakonim Limited",
                 "reaper-enterprises.co.uk": "Reaper Enterprises Ltd",
                 "uu.net": "Verizon Business",
                 "cbsig.net.": "CBS Corporation Inc.",
                 "ge.com.": "General Electric Company",
                 "cmhosts.net.": "Cyber Media Solutions Ltd",
                 "serco.com.": "Serco Group plc",
                 "qinetiq.com.":"QINETIQ GROUP PLC",
                 "hpe.com.": "Hewlett Packard Enterprise Company",
                 "capgemini.com.": "Capgemini",
                 "atos.net.": "ATOS SE",
                 "bac.com.":"Bank of America",
                 "barcap.com.":"Barclays Bank PLC",
                 "nstld.com.":"VERISIGN INC.",
                 "nsroot2.com.":"CitiBank, N.A.",
                 "lon2.telecity.net.":"TelecityGroup International Ltd",
                 "commerzbank.com.":"Commerzbank AG",
                 "credit-suisse.com.":"Credit Suisse Group AG",
                 "db.com.":"Deutsche-Bank Group",
                 "ebrd.com.":"European Bank for Reconstruction and Development",
                 "euroclear.com.":"Euroclear SA/NV",
                 "hsbc":"HSBC Group Management Services Limited",
                 "jpmorganchase.com.":"JPMorgan Chase & Co.",
                 "lloydsbanking":"Lloyds Bank Plc",
                 "lloydstsb":"Lloyds TSB Bank Plc",
                 "borsait.net.":"London Stock Exchange Group PLC",
                 "thelseg.net.":"London Stock Exchange Group PLC",
                 "ms.com.": "Morgan Stanley",
                 "morganstanley.net.": "Morgan Stanley",
                 "nationet.net.": "Nationwide Building Society",
                 "googledomains.com.": "Google Inc.",
                 "verisigndns.com.": "VeriSign, Inc.",
                 "atlasisp.net.": "Atlas Communications (NI) Ltd.",
                 "attdns.com.": "AT&T SERVICES, INC.",
                 "ubs.com.": "UBS Group AG",
                 "thomsonreuters.net.": "Thomson Reuters Global Resources Unlimited Company",
                 "statestreet.com.": "State Street Corporation",
                 "sgcib.com.": "SOCIETE GENERALE",
                 "bbc.net.uk": "BBC",
                 "bbc.co.uk": "BBC",
                 "123-reg.co.uk.":"Webfusion Limited",
                 "telecity.net.":"TelecityGroup International Ltd",
                 "bt.com.":"BRITISH TELECOMMUNICATIONS PLC",
                 "gigaclear.com.":"Gigaclear plc",
                 "he.net.":"Hurricane Electric Hostmaster",
                 "worldnic.com.":"Network Solutions LLC",
                 "converged.co.uk.":"Converged Communication Solutions Limited",
                 "CustodianDC.com.":"CustodianDC Ltd",
                 "custdc.net.":"CustodianDC Ltd",
                 "gcicom.net.":"GCI",
                 "hello-telecom.co.uk.":"Aqua",
                 "Level3.net.":"Level 3 Communications, LLC",
                 "performgroup.com.":"PERFORM MEDIA SERVICES LIMITED",
                 "pmgchosting.com.":"PMGC Managed Services Ltd",
                 "pa.press.net.":"PA Group Limited",
                 "provu.co.uk.":"ProVu Communications Ltd",
                 "comlaude.net.":"Com Laude",
                 "comlaude.co.uk.":"Com Laude",
                 "newsint.co.uk.":"News UK & Ireland Limited",
                 "liquidtelecom.net.":"Liquid Telecommunications Limited",
                 "associated.co.uk.":"Associated Newspapers Limited",
                 "manchestermetronet.com.":"Metronet (UK) Ltd",
                 "widexs.net.":"WideXS",
                 "vodafone.com.":"Vodafone Group Plc",
                 "eyi.com.":"EYGN Limited",
                 "gs360.net.":"Goldman Sachs & Co.",
                 "goldmansachs.info.":"Goldman Sachs & Co. HQ",
                 "gs.com.":"Goldman Sachs & Co.",
                 "goldmansachs.biz.":"Goldman Sachs & Co. HQ",
                 "lch.com.":"LONDON STOCK EXCHANGE PLC",
                 "us.socgen.com.":"Societe Generale",
                 "nsroot1.com.":"Citibank, N.A.",
                 "socgen.co.jp.":"Societe Generale Aircraft Leasing",
                 "dtag.net.":"Deutsche Telekom AG, Domainmanagement",
                 "keycom.co.uk.":"Gateway Global Communications Limited",
                 "ic.net.uk.":"Internet Central Limited",
                 "i4ihosting.com.":"IMAGES FOR INDUSTRY LTD",
                 "gigaclear.net.":"Gigaclear plc",
                 "zoneedit.co.uk.":"easyDNS Technologies Inc.",
                 "netsource.ie": "Netsource Ltd",
                 "ultradns.co.uk.":"UltraDNS Corporation",
                 "microlite1.com.":"WEBSENSATION LTD",
                 "esdns.net.":"DXC Technology",
                 "rockfordhost.co.uk.":"Rockford IT Limited",
                 "premierenergy.co.uk.":"Premier Energy Services Ltd",
                 "ui-dns.biz.":"1&1 Internet AG",
                 "toshiba-europe.com.":"Toshiba of Europe Ltd",
                 "fiat.it": "Fiat Group Automobiles Spa",
                 "axis.com.":"Axis Communications AB",
                 "socgen.com.":"Societe Generale",
                 "eircom.net.":"Eircom Ltd",
                 "merseyfire.gov.uk.":"Merseyside Fire and Rescue Service",
                 "lond-amb.nhs.uk.":"Department of Health",
                 "tnp.net.uk.":"The Networking People (North West) Limited",
                 "dns.gandi.net.":"Gandi SAS",
                 "level3.net.":"Level 3 Communications, LLC",
                 "mobil.com.":"Exxon Mobil Corporation",
                 "essarair.com.":"Essar Steel Limited",
                 "northernpowergrid.com.":"Northern Powergrid Holdings",
                 "comlaude-dns.net.":"Nom IQ Ltd. DBA Com Laude",
                 "comlaude-dns.co.uk.":"Nom IQ Ltd. DBA Com Laude",
                 "scottish-southern.co.uk.":"SSE PLC",
                 "ttd.net.":"TELEFONICA, S.A.",
                 "nationalgrid.com.":"NationalGridUSA Service Company, Inc.",
                 "widexs.nl": "KPN Internedservices",
                 "scotnet.co.uk.":"Foremost IT Ltd",
                 "talkinternet.co.uk.":"Talk Internet Ltd",
                 "talk-101.co.uk.":"Talk Internet Ltd",
                 "mp2000.net.":"MP2000",
                 "lcn.com.":"LCN.com Ltd",
                 "fiatservices.it.":"Fiat Group Automobiles Spa",
                 "unisys.co.uk.":"Unisys",
                 "unisys.com.":"Unisys",
                 "bnpparibas.com":"BNP Paribas",
                 "savvis.net.":"Colorado WSC, LLC",
                 "rrpproxy.net.":"Key-Systems GmbH",
                 "iveco.com.":"Iveco S.p.A.",
                 "shell.com.":"Shell International Petroleum Company Limited",
                 "domivesta.com.":"BNP Paribas",
                 "muni.org.":"Municipality of Anchorage","thinkco.com.":"ThinkCo Ltd",
                 "advsys.co.uk.":"Domicilium (IOM) LTD",
                 "iom.com.":"Domicilium IOM Ltd",
                 "oscura.net.":"Oscura Ltd",
                 "easily.co.uk.":"NetNames Limited",
                 "dtag.de":"Deutsche Telekom AG",
                 "domivesta.net.":"BNP Paribas",
                 "entornodns.com":"EntornoDigital, S.A.",
                 "totalfinaelf.net":"TOTAL s.a",
                 "valero.com":"Valero Energy",
                 "beaming.info":"Beaming Ltd",
                 "anlremote.com.":"Associated Newspapers Limited",
                 "ericy.com.":"Telefonaktiebolaget L M Ericsson",
                 "nationalit.co.uk.": "Chris Smith",
                 "londonstockexchange.com": "London Stock Exchange Group PLC"

                 }


mx_providers = {'google.com': 'Google',
                'GOOGLE.COM': 'Google',
                'googlemail.com': 'Google',
                'outlook.com': 'Microsoft',
                'messagelabs.com': 'Symantec Messagelabs',
                'mimecast.com': 'Mimecast',
                'mailcontrol.com': 'Forcepoint',
                'avgcloud.net': 'AVG',
                'fusemail.net': 'FuseMail',
                'emailsrvr.com': 'Rackspace',
                'pulsant.com': 'Pulsant',
                'netnames.net': 'Netnames',
                'hcidata.com': 'HCI Data',
                'nexus.org.uk': 'Tyne and Wear Public Transport Executive',
                'zen.co.uk': 'Zen Internet'
                }


cdn_providers = {'.clients.turbobytes.net': 'TurboBytes',
                ".turbobytes-cdn.com": "TurboBytes",
                ".afxcdn.net": "afxcdn.net",
                ".akamai.net": "Akamai",
                ".akamaiedge.net": "Akamai",
                ".akadns.net": "Akamai",
                ".akamaitechnologies.com": "Akamai",
                ".gslb.tbcache.com": "Alimama",
                ".cloudfront.net": "Amazon Cloudfront",
                ".anankecdn.com.br": "Ananke",
                ".att-dsa.net": "AT&T",
                ".azioncdn.net": "Azion",
                ".belugacdn.com": "BelugaCDN",
                ".bluehatnetwork.com": "Blue Hat Network",
                ".systemcdn.net": "EdgeCast",
                ".cachefly.net": "Cachefly",
                ".cdn77.net": "CDN77",
                ".cdn77.org": "CDN77",
                ".panthercdn.com": "CDNetworks",
                ".cdngc.net": "CDNetworks",
                ".gccdn.net": "CDNetworks",
                ".gccdn.cn": "CDNetworks",
                ".cdnify.io": "CDNify",
                ".ccgslb.com": "ChinaCache",
                ".ccgslb.net": "ChinaCache",
                ".c3cache.net": "ChinaCache",
                ".chinacache.net": "ChinaCache",
                ".c3cdn.net": "ChinaCache",
                ".lxdns.com": "ChinaNetCenter",
                ".speedcdns.com": "QUANTIL/ChinaNetCenter",
                ".cloudflare.com": "Cloudflare",
                ".cloudflare.net": "Cloudflare",
                ".edgecastcdn.net": "EdgeCast",
                ".adn.": "EdgeCast",
                ".wac.": "EdgeCast",
                ".wpc.": "EdgeCast",
                ".fastly.net": "Fastly",
                ".fastlylb.net": "Fastly",
                ".google.": "Google",
                "googlesyndication.": "Google",
                "youtube.": "Google",
                ".googleusercontent.com": "Google",
                ".l.doubleclick.net": "Google",
                ".hiberniacdn.com": "Hibernia",
                ".hwcdn.net": "Highwinds",
                ".incapdns.net": "Incapsula",
                ".inscname.net": "Instartlogic",
                ".insnw.net": "Instartlogic",
                ".internapcdn.net": "Internap",
                ".kxcdn.com": "KeyCDN",
                ".lswcdn.net": "LeaseWeb CDN",
                ".footprint.net": "Level3",
                ".llnwd.net": "Limelight",
                ".lldns.net": "Limelight",
                ".netdna-cdn.com": "MaxCDN",
                ".netdna-ssl.com": "MaxCDN",
                ".netdna.com": "MaxCDN",
                ".mncdn.com": "Medianova",
                ".instacontent.net": "Mirror Image",
                ".mirror-image.net": "Mirror Image",
                ".cap-mii.net": "Mirror Image",
                ".rncdn1.com": "Reflected Networks",
                ".simplecdn.net": "Simple CDN",
                ".swiftcdn1.com": "SwiftCDN",
                ".swiftserve.com": "SwiftServe",
                ".gslb.taobao.com": "Taobao",
                ".cdn.bitgravity.com": "Tata communications",
                ".cdn.telefonica.com": "Telefonica",
                ".vo.msecnd.net": "Windows Azure",
                ".ay1.b.yahoo.com": "Yahoo",
                ".yimg.": "Yahoo",
                ".zenedge.net": "Zenedge"
}